name: Publish to Modrinth

on:
  push:
    tags:
      - '*'  # Runs on tag pushes (e.g., v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Debug Environment Variables
        run: |
          if [[ -z "${MODRINTH_TOKEN}" ]]; then
            echo "MODRINTH_TOKEN is NOT set"
            exit 1
          else
            echo "MODRINTH_TOKEN is set"
          fi
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

      - name: Build the Mod
        run: ./gradlew build

      - name: Publish to Modrinth
        run: MODRINTH_TOKEN=${{ secrets.MODRINTH_TOKEN }} ./gradlew modrinth